linux_builds:
  tags: 
  - linux
  only:
  - develop
  image: matteoragni/clothoids.build.antemotion.com:latest
  script:
  - |
    cd src_py
    mkdir build3.6
    cd build3.6
    cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6 ..
    make
    cd ..
    /usr/bin/python3.6 test
    mkdir -p $CI_PROJECT_DIR/releases/linux/python3.6
    cp build3.6/G2lib.cpython-36m-x86_64-linux-gnu.so $CI_PROJECT_DIR/releases/linux/python3.6
    mkdir build3.7
    cd build3.7
    cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.7 ..
    make
    cd ..
    /usr/bin/python3.7 test
    mkdir -p $CI_PROJECT_DIR/releases/linux/python3.7
    cp build3.7/G2lib.cpython-36m-x86_64-linux-gnu.so $CI_PROJECT_DIR/releases/linux/python3.7
    mkdir build2.7
    cd build2.7
    cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7 ..
    make
    cd ..
    /usr/bin/python2.7 test
    mkdir -p $CI_PROJECT_DIR/releases/linux/python2.7
    cp build2.7/G2lib.so $CI_PROJECT_DIR/releases/linux/python2.7
  artifacts:
    paths:
    - releases
